# Generated by Django 2.1.4 on 2018-12-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'chem_class',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='EI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Едиица измерения',
                'verbose_name_plural': 'Еденицы измерения',
                'db_table': 'ei',
            },
        ),
        migrations.CreateModel(
            name='Enum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'enum',
            },
        ),
        migrations.CreateModel(
            name='EnumVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
                ('id_enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Enum')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'enum_val',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Materials')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Ord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date_reg', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Customer')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'ord',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
                ('ei_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.EI')),
                ('id_enum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Enum')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'db_table': 'parametr',
            },
        ),
        migrations.CreateModel(
            name='ParClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_val', models.IntegerField(null=True)),
                ('max_val', models.IntegerField()),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.ChemClass')),
                ('id_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Parameter')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'par_class',
            },
        ),
        migrations.CreateModel(
            name='ParProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField()),
                ('note', models.CharField(max_length=255)),
                ('id_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Parameter')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'par_prod',
            },
        ),
        migrations.CreateModel(
            name='PosOrd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pos', models.IntegerField()),
                ('sums', models.FloatField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Ord')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'pos_ord',
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
                ('conf', models.FloatField()),
                ('id_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.ChemClass')),
                ('type_prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Prod')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'prod',
            },
        ),
        migrations.CreateModel(
            name='TypePar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'type_par',
            },
        ),
        migrations.AddField(
            model_name='posord',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Prod'),
        ),
        migrations.AddField(
            model_name='parprod',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Prod'),
        ),
        migrations.AddField(
            model_name='parprod',
            name='id_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.EnumVal'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.TypePar'),
        ),
        migrations.AddField(
            model_name='materials',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Prod'),
        ),
        migrations.AddField(
            model_name='chemclass',
            name='base_ei',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.EI'),
        ),
        migrations.AddField(
            model_name='chemclass',
            name='main_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.ChemClass'),
        ),
    ]
