# Generated by Django 2.1.4 on 2018-12-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181223_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemclass',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя класса изделия'),
        ),
    ]
